# Generated by Django 6.0.6 on 2026-06-17 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_completed', models.BooleanField(default=False, verbose_name='concluída')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='recompensa de XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
